apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-deployment
  labels:
    app: bid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bid
  template:
    metadata:
      labels:
        app: bid
    spec:
      containers:
      - name: bid
        image: feed1119/panda-bid:720066b64d26dbff1d0bb3a0c66f429609f9f1ab
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: bid-storage
          mountPath: /app
      volumes:
      - name: bid-storage
        persistentVolumeClaim:
          claimName: bid-pvc 
---
apiVersion: v1
kind: Service
metadata:
  name: bid-service
spec:
  selector:
    app: bid
  ports:
    - protocol: TCP
      port: 8083  # 서비스에 노출되는 포트
      targetPort: 8081  # 파드에 포워딩되는 포트
      nodePort: 31200  # 변경 가능: 노드 포트 번호 (30000 ~ 32767 사이의 값을 선택)
  type: NodePort  # 서비스 유형을 NodePort로 변경
  
